### ISSUE TITLE
Feature Request: Maximize, Unmaximize, Minimize, Activate, Resize, Move, Close

### ISSUE THREAD

**Issue by blueray453** [ickyicky/window-calls#1]
Get Active Window ID.

Ex. 

```
$ ACTIVEWINDOWID=$(gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell/Extensions/Windows --method org.gnome.Shell.Extensions.Windows.GetActiveWindow)
$ echo ACTIVEWINDOWID
  {
    "class": "firefox",
    "pid": 17717,
    "id": 1140312238,
    "maximized": 0,
    "focus": false,
    "title": "xdotool hang if I tile / snap the window — Mozilla Firefox"
  }
```

Get Active Workspace.
```
$ WORKSPACE=$(gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell/Extensions/Windows --method org.gnome.Shell.Extensions.Windows.GetWorkspace)
```
We would like to Maximize, Unmaximize, Minimize, Activate, Resize, Move, Close by WindowID

Example of Maximize, Move, Size etc
```
gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell/Extensions/Windows --method org.gnome.Shell.Extensions.Windows.Maximize 2205525109 

gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell/Extensions/Windows --method org.gnome.Shell.Extensions.Windows.Unmaximize 2205525109 

gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell/Extensions/Windows --method org.gnome.Shell.Extensions.Windows.Minimize 2205525109 

gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell/Extensions/Windows --method org.gnome.Shell.Extensions.Windows.Activate 2205525109 

gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell/Extensions/Windows --method org.gnome.Shell.Extensions.Windows.Move 2205525109 X Y

gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell/Extensions/Windows --method org.gnome.Shell.Extensions.Windows.Size 2205525109 Width Height

gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell/Extensions/Windows --method org.gnome.Shell.Extensions.Windows.Close 2205525109 
```
Few More values will be great with GetActiveWindow
```
$ echo ACTIVEWINDOWID
  {
    "class": "firefox",
    "pid": 17717,
    "id": 1140312238,
    "maximized": 0,
    "focus": false,
    "title": "xdotool hang if I tile / snap the window — Mozilla Firefox"
    "class_instance": "get_wm_class_instance",
    "width": 
    "height": 
    "x-coordinate": 
    "y-coordinate": 
    "workspace_of_current_window": 
    "IsViewable":
  }
```

Here, `IsViewable` is the value shown with in `xwininfo`'s output's `Map State: IsViewable`. This is same as `xdotools`'s `--onlyvisible`.

That is all we need.

**Comment by blueray453** [comment]
This is how far I got. The API is unstable and documentation is too bad. I can not go any further.

```
const { Gio } = imports.gi;

const MR_DBUS_IFACE = `
<node>
    <interface name="org.gnome.Shell.Extensions.Windows">
        <method name="ListWindows">
            <arg type="s" direction="out" name="winJsonArr"/>
        </method>
    </interface>
</node>`;


class Extension {
    enable() {
        this._dbus = Gio.DBusExportedObject.wrapJSObject(MR_DBUS_IFACE, this);
        this._dbus.export(Gio.DBus.session, '/org/gnome/Shell/Extensions/Windows');
    }

    disable() {
        this._dbus.flush();
        this._dbus.unexport();
        delete this._dbus;
    }
    ListWindows() {
        let win = global.get_window_actors();

        let workspaceManager = global.workspace_manager;
        let currentmonitor = global.display.get_current_monitor();
        let monitor = global.display.get_monitor_geometry(currentmonitor);
        //let activeWorkspace = workspaceManager.get_active_workspace_index();


        var winJsonArr = [];
        win.forEach(function (w) {
            winJsonArr.push({
                class: w.meta_window.get_wm_class(),
                class_instance: w.meta_window.get_wm_class_instance(),
                pid: w.meta_window.get_pid(),
                id: w.meta_window.get_id(),
                width: w.get_width(),
                height: w.get_height(),
                x: w.get_x(),
                y: w.get_y(),
                maximized: w.meta_window.get_maximized(),
                focus: w.meta_window.has_focus(),
                title: w.meta_window.get_title(),
                workspace: w.meta_window.located_on_workspace(workspaceManager.get_active_workspace()),
                moveable: w.meta_window.allows_move(),
                resizeable: w.meta_window.allows_resize(),
                canclose: w.meta_window.can_close(),
                canmaximize: w.meta_window.can_maximize(),
                canminimize: w.meta_window.can_minimize(),
                canshade: w.meta_window.can_shade(),
                display: w.meta_window.get_display(),
                frame_bounds: w.meta_window.get_frame_bounds(),
                frame_type: w.meta_window.get_frame_type(),
                window_type: w.meta_window.get_window_type(),
                layer: w.meta_window.get_layer(),
                monitor: w.meta_window.get_monitor(),
                role: w.meta_window.get_role(),
                area: w.meta_window.get_work_area_current_monitor(),
                area_all: w.meta_window.get_work_area_all_monitors(),
                area_cust: w.meta_window.get_work_area_for_monitor(currentmonitor)
            });
        })

        return JSON.stringify(winJsonArr);
    }
}

function init() {
    return new Extension();
}
```

You can view the output with `gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell/Extensions/Windows --method org.gnome.Shell.Extensions.Windows.ListWindows | cut -c 3- | rev | cut -c4- | rev | jq .`

**Comment by ickyicky** [comment]
I added requested functionality through new available methods:
`			  <method name="MoveResize">
            <arg type="u" direction="in" name="winid"/>
            <arg type="u" direction="in" name="width"/>
            <arg type="u" direction="in" name="height"/>
            <arg type="u" direction="in" name="x"/>
            <arg type="u" direction="in" name="y"/>
        </method>
			  <method name="Resize">
            <arg type="u" direction="in" name="winid"/>
            <arg type="u" direction="in" name="width"/>
            <arg type="u" direction="in" name="height"/>
        </method>
			  <method name="Move">
            <arg type="u" direction="in" name="winid"/>
            <arg type="u" direction="in" name="x"/>
            <arg type="u" direction="in" name="y"/>
        </method>
			  <method name="Maximize">
            <arg type="u" direction="in" name="winid"/>
        </method>
			  <method name="Minimize">
            <arg type="u" direction="in" name="winid"/>
        </method>
			  <method name="Unmaximize">
            <arg type="u" direction="in" name="winid"/>
        </method>
			  <method name="Unminimize">
            <arg type="u" direction="in" name="winid"/>
        </method>
			  <method name="Activate">
            <arg type="u" direction="in" name="winid"/>
        </method>
			  <method name="Close">
            <arg type="u" direction="in" name="winid"/>
        </method>
`
For example, you can close given window by calling:
`gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell/Extensions/Windows --method org.gnome.Shell.Extensions.Windows.Close <winid>`

Currently I'm at holidays, so I'll add documentation for new methods in about a week to readme, I'll leave issue opened till then :) Extension update should be visible any moment, as I still wait for review of new version.

**Comment by ickyicky** [comment]
Also huge thanks for sample window properties I can return, added all of them to extension code.

**Comment by blueray453** [comment]
Create first.json file

    gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell/Extensions/Windows --method org.gnome.Shell.Extensions.Windows.ListWindows > first.json

All WindowID In Current Workspace

    cat first.json | jq -c '.[] | select (.workspace == true) | .id'

All WindowID and wm_class In Current Workspace

    cat first.json | jq -c '[.[] | select (.workspace == true) | {id: .id,wm_class: .wm_class}]'

All WindowID and wm_class of Visible Window

    cat first.json | jq -c '[.[] | select (.frame_type == 0 and .window_type == 0) | {id: .id,wm_class: .wm_class}]'

All WindowID and wm_class Visible Window In Current Workspace

    cat first.json | jq -c '[.[] | select (.workspace == true and .frame_type == 0 and .window_type == 0) | {id: .id,wm_class: .wm_class}]'

I had to remove `title: w.meta_window.get_title()` because if there is quote, slash etc. in the title then `jq` sometimes do not parse. More details in https://github.com/stedolan/jq/issues/2471

**Comment by blueray453** [comment]
**Meta.WindowType** 

NORMAL = 0 — Normal
DESKTOP = 1 — Desktop
DOCK = 2 — Dock
DIALOG = 3 — Dialog
MODAL_DIALOG = 4 — Modal dialog
TOOLBAR = 5 — Toolbar
MENU = 6 — Menu
UTILITY = 7 — Utility
SPLASHSCREEN = 8 — Splashcreen
DROPDOWN_MENU = 9 — Dropdown menu
POPUP_MENU = 10 — Popup menu
TOOLTIP = 11 — Tooltip
NOTIFICATION = 12 — Notification
COMBO = 13 — Combobox
DND = 14 — Drag and drop
OVERRIDE_OTHER = 15 — Other override - redirect window type


**Meta.FrameType**

NORMAL = 0 — Normal frame
DIALOG = 1 — Dialog frame
MODAL_DIALOG = 2 — Modal dialog frame
UTILITY = 3 — Utility frame
MENU = 4 — Menu frame
BORDER = 5 — Border frame
ATTACHED = 6 — Attached frame
LAST = 7 — Marks the end of the Meta.FrameType enumeration

**Comment by ickyicky** [comment]
Since the amount of information returned by List has greatly increased I suggest dividing method into two separate calls:
- List, that would return just the basic information about window: id, class, pid etc
- Details, that would return all other information about the window, for example problematic title
It would be great if You told me what information you need from List method, and what is acceptable to move to Details one. Also, I can include boolean call parameter that would disable returning string values risky of containing problematic double "\", which for now only title is

**Comment by blueray453** [comment]
Yes this is important to remove unnecessary details. I went through all of those just to check what we need. Ultimately I settled down to:

```
win.forEach(function (w) {
            winJsonArr.push({
              wm_class: w.meta_window.get_wm_class(),
              wm_class_instance: w.meta_window.get_wm_class_instance(),
              pid: w.meta_window.get_pid(),
              id: w.meta_window.get_id(),
              frame_type: w.meta_window.get_frame_type(),
              window_type: w.meta_window.get_window_type(),
              width: w.get_width(),
              height: w.get_height(),
              x: w.get_x(),
              y: w.get_y(),
              in_current_workspace: w.meta_window.located_on_workspace(workspaceManager.get_active_workspace()),
                monitor: w.meta_window.get_monitor()
            });
        })
```

**Comment by blueray453** [comment]
Error: GDBus.Error:org.gnome.gjs.JSError.ReferenceError: w is not defined

```
% gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell/Extensions/Windows --method org.gnome.Shell.Extensions.Windows.List | cut -c 3- | rev | cut -c4- | rev | jq -c '[.[] | select (.in_current_workspace == true and .frame_type == 0 and .window_type == 0) | {id: .id,wm_class: .wm_class}]' | jq .
[
  {
    "id": 1394707466,
    "wm_class": "firefox"
  },
  {
    "id": 1394707474,
    "wm_class": "Nemo"
  },
  {
    "id": 1394707476,
    "wm_class": "Nemo"
  },
  {
    "id": 1394707468,
    "wm_class": "Fsearch"
  },
  {
    "id": 1394707469,
    "wm_class": "firefox"
  },
  {
    "id": 1394707470,
    "wm_class": "VSCodium"
  },
  {
    "id": 1394707475,
    "wm_class": "Nemo"
  },
  {
    "id": 1394707477,
    "wm_class": "Alacritty"
  }
]
% gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell/Extensions/Windows --method org.gnome.Shell.Extensions.Windows.MoveResize 1394707477 1000 1000 100 100
Error: GDBus.Error:org.gnome.gjs.JSError.ReferenceError: w is not defined
```
what am i doing wrong?

**Comment by ickyicky** [comment]
You found bug in MoveResize, I patched it in lastest release alongside with simplyfying List result, adding Details method and GetTitle method. Should be available any minute now, you can browse changes [here](https://github.com/ickyicky/window-calls/commit/94362b01fc7588bc73a01553defa4f427a81a689)

**Comment by ickyicky** [comment]
New version is now available on [extensions.gnome](https://extensions.gnome.org/extension/4724/window-calls/)

**Comment by ickyicky** [comment]
Recent pull requests have been published to gnome extensions and available for installation. I will extensively test everything in a week, for now i added documentation to Readme (alongside jq usage from PR)
