### ISSUE TITLE
Gnome crash when calling Details

### ISSUE THREAD

**Issue by normanr** [ickyicky/window-calls#10]
I'm using Gnome 43 running under X11, and when Details calls `meta_window.get_frame_bounds()` gnome-shell crashes.

```../gi/cwrapper.h:169: static void CWrapperPointerOps<Base, Wrapped>::init_private(JSObject*, Wrapped*) [with Base = CairoRegion; Wrapped = _cairo_region]: Assertion `ptr && "private pointer should not be null, use unset_private"' failed.```.

Commenting out the call to `get_frame_bounds()` prevents the crash.

I wonder if it's related the return type being `cairo.Region` (there are no other `cairo` types in `meta.window`)~, or maybe because it's running under X11 instead of Wayland~.

**Comment by Cherro59** [comment]
This happens on wayland too

**Comment by ickyicky** [comment]
This is something within calling `get_frame_bounds()`, not processing it's result. For now i just moved `frame_bounds` from `Details` call to new `GetFrameBounds` one so `Details` is usable. Issue is also present in Gnome 44.

Newest 14 version of the extension should work correctly
