### ISSUE TITLE
Plugin can no longer be installed or updated on gnome 42.9

### ISSUE THREAD

**Issue by rbnswartz** [ickyicky/window-calls#15]
Got an error when trying to update to the most recent version of the extension. Didn't crash the system or anything just sitting in a very generic and entirely unhelpful "error" state
![image](https://github.com/ickyicky/window-calls/assets/724704/bb55f592-b678-469b-a6f9-741734390257)

I'm using ubuntu 22.04.3 LTS
Gnome version: 42.9
Windowing System: Wayland

Please let me know what other details I can give or troubleshooting I can do

**Comment by ickyicky** [comment]
Did you change anything within extension? Checked on both LTS and most recent ubuntu, either updating and fresh install works for me, unless you have local files with some changes, then extension update fails since it is not able to resolve how to merge both versions

**Comment by ickyicky** [comment]
I can advice deleting `~/.local/share/gnome-shell/extensions/window-calls@domandoman.xyz` folder and trying to install extension then

**Comment by rbnswartz** [comment]
Come to think of it I had tried tinkering with it to add some functionality. Removing it didn't help until I restarted shell. Sorry for the false alarm.
