### ISSUE TITLE
Output is not in JSON Format

### ISSUE THREAD

**Issue by blueray453** [ickyicky/window-calls#2]
when i run 

    gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell/Extensions/Windows --method org.gnome.Shell.Extensions.Windows.List

The output is not in json format. It looks like

    ('[{" ... "}]',)

I have to run:

    gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell/Extensions/Windows --method org.gnome.Shell.Extensions.Windows.List | cut -c 3- | rev | cut -c4- | rev | jq .

to get the json output.

Output in json would be great.

**Comment by ickyicky** [comment]
I don't think theres way to output pure JSON from gdbus call, I was experimenting with returning types such as aa{sv} (aray of aray of string: value pair) and it is even worse to manipulate using jq or any other json parser. I suggest capturing JSON result using regex, for example using gawk:
`gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell/Extensions/Windows --method org.gnome.Shell.Extensions.Windows.List | gawk 'match($0, /\[.*\]/, a) {print a[0]}'`

**Comment by normanr** [comment]
`dbus-send --print-reply=literal --session --dest=org.gnome.Shell /org/gnome/Shell/Extensions/Windows org.gnome.Shell.Extensions.Windows.List` is a good alternative. Its output can be passed directly to `jq`.
