### ISSUE TITLE
[Feature Request] Can we get the focus status directly from List?

### ISSUE THREAD

**Issue by zw963** [ickyicky/window-calls#7]
I know this extension from arch form [here](https://bbs.archlinux.org/viewtopic.php?id=280270)

as you can see discuss there, current get all active windows, if we can know the focus status, that will help a lot

so, can we add a `focus` attribute to `org.gnome.Shell.Extensions.Windows.List` output?

Thank you.

**Comment by zw963** [comment]
We need a way to get current workspace number too, otherwize, when switch to a workspace, how to know current workspace number when run following command?

```
gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell/Extensions/Windows --method org.gnome.Shell.Extensions.Windows.MoveToWorkspace 2205525109 4
```

**Comment by zw963** [comment]
Hi, please check this discuss too

https://bbs.archlinux.org/viewtopic.php?pid=2062142#p2062142

**Comment by ickyicky** [comment]
Sure, I will add it tomorrow. As for focus, I will investigate the issue and probably will merge proposed solution into the code together with adding focus to list result

**Comment by zw963** [comment]
Okay, BTW, as i describe in above thread, following activate feature not work.

```
    Activate(winid) {
        let win = this._get_window_by_wid(winid).meta_window;
        if (win) {
            win.activate(Math.floor(Date.now() / 1000));
        } else {
            throw new Error('Not found');
        }
    }
```

I have to change to:

```
    Activate(winid) {
        let win = this._get_window_by_wid(winid).meta_window;
        if (win) {
            win.activate(0);
        } else {
            throw new Error('Not found');
        }
    }
```

To make the code working.

Thanks

**Comment by zw963** [comment]
I create a PR for this, please check.

https://github.com/ickyicky/window-calls/pull/8

After changes, it work quite well on my GNONE + Wayland for a  purpose of command line tool for switch to one program and back.

**Comment by zw963** [comment]
#8 merged, thank you.

**Comment by zw963** [comment]
Hi, do you know how to restart gnome shell but without need restart the gnome session?

i expect install this extension from command line.

1.  copy this extension to ~/.local/share/gnome-shell/extension
2.  i want to restart gnome extension, to make this extension available immediately, but i don't how.
     for now, i have to logout and login to make this extension available.

thank you.
